[package]
name = "ktls-uring-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.180"
nix = { version = "0.29", features = ["socket"] }
rustls = "0.23.36"
rustls-native-certs = "0.8.3"
tokio-uring = "0.5.0"
